mtList<- function(){
fList <- list()
fList[["LL.2"]] <- list(fct = paste("1/(1 + exp(b * log(dose/e)))"), poc = "b")
fList[["LL.3"]] <- list(fct = paste("d/(1 + exp(b * log(dose/e)))"), poc = "b")
fList[["LL.4"]] <- list(fct = paste("c + (d - c)/(1 + exp(b * log(dose/e)))"), poc = "b")
fList[["LL.5"]] <- list(fct = paste("c + (d - c)/(1 + exp(b * log(dose/e))^f"), poc = "b")
fList[["LL.2"]] <- list(fct = paste("1/(1 + exp(b * log(dose/e)))"), poc = "b")
fList[["LL.3u"]] <- list(fct = paste("c + (1 - c)/(1 + exp(b * log(dose/e)))"), poc = "b")
fList[["W1.2"]] <- list(fct = paste("exp(-exp(b * (log(dose) - log(e))))"), poc = "b")
fList[["W1.3"]] <- list(fct = paste("d * exp(-exp(b * (log(dose) - log(e))))"), poc = "b")
fList[["W1.4"]] <- list(fct = paste("c + (d - c) * exp(-exp(b * (log(dose) - log(e))))"), poc = "b")
fList[["W2.2"]] <- list(fct = paste("(1 - exp(-exp(b * (log(dose) - log(e)))))"), poc = "b")
fList[["W2.3"]] <- list(fct = paste("d * (1 - exp(-exp(b * (log(dose) - log(e)))))"), poc = "b")
fList[["W2.4"]] <- list(fct = paste("c + (d - c) * (1 - exp(-exp(b * (log(dose) - log(e)))))"), poc = "b")
fList[["EXD.2"]] <- list(fct = paste("d*(exp(-dose/e))"), poc = "d")
fList[["EXD.3"]] <- list(fct = paste("c + (d-c)*(exp(-dose/e))"), poc = "d-c")
fList[["FPL.4"]] <- list(fct = paste("c + (d-c)/(1 + exp(b * (log(dose + 1))^p1 + e * (log(dose + 1))^p2))"), poc = "d-c")
fList[["AR.3"]] <- list(fct = paste("c + (d-c)*(1-exp(-dose/e))"), poc = "d-c")
fList[["AR.2"]] <- list(fct = paste("d*(1-exp(-dose/e))"), poc = "d-c")
fList[["G.4"]] <- list(fct = paste("c + (d-c)*(exp(-exp(b*(dose-e))))"), poc = "d-c")
fList[["G.3"]] <- list(fct = paste("d*(exp(-exp(b*(dose-e))))"), poc = "d-c")
fList[["G.2"]] <- list(fct = paste("exp(-exp(b*(dose-e)))"), poc = "d-c")
fList[["G.3u"]] <- list(fct = paste("c + (1-c)*(exp(-exp(b*(dose-e))))"), poc = "1-c")
fList[["L.5"]] <- list(fct = paste("c + (d-c)/((1+exp(b*(dose - e)))^f)"), poc = "d-c")
fList[["L.4"]] <- list(fct = paste("c + (d-c)/(1+exp(b*(dose - e)))"), poc = "d-c")
fList[["L.3"]] <- list(fct = paste("d/(1+exp(b*(dose - e)))"), poc = "d")
fList[["LL2.5"]] <- list(fct = paste("c + (d-c)/((1+exp(b*(log(dose)-log(e))))^f)"), poc = "b")
fList[["LL2.4"]] <- list(fct = paste("c + (d-c)/(1+exp(b*(log(dose)-log(e))))"), poc = "b")
fList[["LL2.3"]] <- list(fct = paste("d/(1+exp(b*(log(dose)-log(e))))"), poc = "b")
fList[["LL2.3"]] <- list(fct = paste("c + (1-c)/(1+exp(b*(log(dose)-log(e))))"), poc = "b")
fList[["LL2.2"]] <- list(fct = paste("1/(1+exp(b*(log(dose)-log(e))))"), poc = "b")
fList[["MM.3"]] <- list(fct = paste("c + (d-c)/(1+(e/dose))"), poc = "d-c")
fList[["MM.2"]] <- list(fct = paste("d/(1+(e/dose))"), poc = "d")
fList
}
