mtList<- function(){
fList <- list()
fList[["LL.2"]] <- paste("1/(1 + exp(b * log(dose/e)))")
fList[["LL.3"]] <- paste("d/(1 + exp(b * log(dose/e)))")
fList[["LL.4"]] <- paste("c + (d - c)/(1 + exp(b * log(dose/e)))")
fList[["LL.5"]] <- paste("c + (d - c)/(1 + exp(b * log(dose/e))^f")
fList[["LL.2"]] <- paste("1/(1 + exp(b * log(dose/e)))")
fList[["LL.3u"]] <- paste("c + (1 - c)/(1 + exp(b * log(dose/e)))")
fList[["W1.2"]] <- paste("exp(-exp(b * (log(dose) - log(e))))")
fList[["W1.3"]] <- paste("d * exp(-exp(b * (log(dose) - log(e))))")
fList[["W1.4"]] <- paste("c + (d - c) * exp(-exp(b * (log(dose) - log(e))))")
fList[["W2.2"]] <- paste("(1 - exp(-exp(b * (log(dose) - log(e)))))")
fList[["W2.3"]] <- paste("d * (1 - exp(-exp(b * (log(dose) - log(e)))))")
fList[["W2.4"]] <- paste("c + (d - c) * (1 - exp(-exp(b * (log(dose) - log(e)))))")
fList[["EXD.2"]] <- paste("d*(exp(-x/e))")
fList[["EXD.3"]] <- paste("c + (d-c)*(exp(-x/e))")
fList[["FPL.4"]] <- paste("c + (d-c)/(1 + exp(b * (log(dose + 1))^p1 + e * (log(dose + 1))^p2))")
fList[["AR.3"]] <- paste("c + (d-c)*(1-exp(-x/e))")
fList[["AR.2"]] <- paste("d*(1-exp(-x/e))")
fList[["G.4"]] <- paste("c + (d-c)*(exp(-exp(b*(x-e))))")
fList[["G.3"]] <- paste("d*(exp(-exp(b*(x-e))))")
fList[["G.2"]] <- paste("exp(-exp(b*(x-e)))")
fList[["G.3u"]] <- paste("c + (1-c)*(exp(-exp(b*(x-e))))")
fList[["L.5"]] <- paste("c + (d-c)/((1+exp(b*(x - e)))^f)")
fList[["L.4"]] <- paste("c + (d-c)/(1+exp(b*(x - e)))")
fList[["L.3"]] <- paste("d/(1+exp(b*(x - e)))")
fList[["LL2.5"]] <- paste("c + (d-c)/((1+exp(b*(log(x)-log(e))))^f)")
fList[["LL2.4"]] <- paste("c + (d-c)/(1+exp(b*(log(x)-log(e))))")
fList[["LL2.3"]] <- paste("d/(1+exp(b*(log(x)-log(e))))")
fList[["LL2.3"]] <- paste("c + (1-c)/(1+exp(b*(log(x)-log(e))))")
fList[["LL2.2"]] <- paste("1/(1+exp(b*(log(x)-log(e))))")
fList[["MM.3"]] <- paste("c + (d-c)/(1+(e/x))")
fList[["MM.2"]] <- paste("d/(1+(e/x))")
fList
}
